### ISSUE TITLE
Panels and Modals are closing automatically

### ISSUE THREAD

**Issue by ViniciusTavares** [zurb/foundation-apps#598]
Hello guys! 

I am using Foundation For Apps in a business application and I am having some problems with panel and modal. They are closing automatically when subsequently opened.

Sample code to open Panel:

```
<li> <a class = "small button" zf-toggle = "panel-portfolio-bidding" zf-close = "panel-portfolio-transactions"  ng-click = "vm.function ()">
   <i class = "fa fa-list-alt"> </ i> Operations History </a> 
</li>
```
In modal if I have a button that closes it with a class and try to reopen it will closes automatically.

ex:
```
<a zf-close="" class="button"> Cancel </a>
```
My Foundation For Apps Version : 1.1.0

See ya!

**Comment by gjungb** [comment]
@ViniciusTavares @gakimball this is related to #547 and #481 due to the animation of the ```button```

**Comment by jeanieshark** [comment]
I'm seeing this fixed as of #547. Please let me know otherwise and I'll reopen!

**Comment by heppy83** [comment]
Hi,
I want to let you know that this issue is still happening.
I posted a comment in #547 but no reply yet.

It would be wonderful if could suggest a solution for this, since it's impossible to use the framework with this happening systematically.

Thank you very much!
